name: Full-Stack CI/CD with Docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx (Docker builder that supports multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers for faster builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Set up Docker (login credentials)
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Docker login to Docker Hub or GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: soumya261412@gmail.com
        password: soumya@docker

    # Build and push Docker images (Backend, Frontend, DB)
    - name: Build and push Docker images
      run: |
        # Build the Docker images using docker-compose.yml
        docker-compose -f docker-compose.yml build

        # Push Docker images to Docker Hub or GitHub Container Registry
        docker-compose -f docker-compose.yml push

    # Deploy the latest Docker images to your server (Optional)
    - name: Deploy to Server
      run: |
        ssh user@server-ip "
          cd /path/to/project && \
          docker-compose pull && \
          docker-compose up -d
        "
